# Generated by Django 6.1.1 on 2026-09-25 15:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('MPESA', 'M-Pesa (not enabled yet)'), ('CARD', 'Card (not enabled yet)')], default='CASH', max_length=20)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('transaction_reference', models.CharField(max_length=100, unique=True)),
                ('payment_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='parking.parkingsession')),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['-payment_time'],
                'indexes': [models.Index(fields=['payment_status'], name='payments_payment_bbdde9_idx'), models.Index(fields=['transaction_reference'], name='payments_transac_4c44f7_idx'), models.Index(fields=['session', 'payment_status'], name='payments_session_017f07_idx')],
            },
        ),
    ]
