# Generated by Django 6.1.1 on 2026-09-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('widget_type', models.CharField(choices=[('METRIC', 'Metric Card'), ('CHART', 'Chart'), ('TABLE', 'Data Table'), ('STATUS_GRID', 'Status Grid'), ('RECENT_ACTIVITY', 'Recent Activity')], default='METRIC', max_length=20)),
                ('data_source', models.CharField(max_length=100)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dashboard_widgets',
                'ordering': ['position', 'name'],
            },
        ),
    ]
