# Generated by Django 6.1.1 on 2026-09-25 15:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(help_text='Kenyan vehicle registration number (e.g., KAA 123A)', max_length=12, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_registration', message='Enter a valid Kenyan registration number (e.g., KAA 123A, KBZ 999Z, KCA 001A)', regex='^K[A-Z]{2}\\s?\\d{1,3}[A-Z]?$')])),
                ('vehicle_type', models.CharField(choices=[('CAR', 'Car'), ('MOTORCYCLE', 'Motorcycle'), ('TRUCK', 'Truck'), ('BUS', 'Bus'), ('OTHER', 'Other')], default='CAR', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vehicles',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['registration_number'], name='vehicles_registr_eb8990_idx'), models.Index(fields=['vehicle_type'], name='vehicles_vehicle_d54349_idx')],
            },
        ),
    ]
