# Generated by Django 6.1.1 on 2026-09-25 15:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('DAILY_SUMMARY', 'Daily Summary'), ('REVENUE', 'Revenue Report'), ('OCCUPANCY', 'Occupancy Report'), ('VEHICLE_HISTORY', 'Vehicle History'), ('PAYMENT_SUMMARY', 'Payment Summary')], max_length=30)),
                ('generated_by', models.CharField(blank=True, max_length=100)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('file_path', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'db_table': 'report_logs',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['report_type'], name='report_logs_report__e5bde3_idx'), models.Index(fields=['generated_at'], name='report_logs_generat_e1551c_idx')],
            },
        ),
    ]
