# Generated by Django 6.1.1 on 2026-09-25 15:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('CAR', 'Car'), ('MOTORCYCLE', 'Motorcycle'), ('TRUCK', 'Truck'), ('BUS', 'Bus'), ('OTHER', 'Other')], default='CAR', max_length=20)),
                ('free_minutes', models.PositiveIntegerField(default=30)),
                ('two_hour_rate', models.DecimalField(decimal_places=2, default=50, max_digits=10)),
                ('four_hour_rate', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                ('six_hour_rate', models.DecimalField(decimal_places=2, default=300, max_digits=10)),
                ('over_six_hour_rate', models.DecimalField(decimal_places=2, default=500, max_digits=10)),
                ('active', models.BooleanField(default=True)),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'parking_rates',
                'ordering': ['-effective_from'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('active', True)), fields=('vehicle_type', 'active'), name='unique_active_rate_per_vehicle_type')],
            },
        ),
        migrations.CreateModel(
            name='ParkingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.CharField(max_length=10, unique=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('MAINTENANCE', 'Maintenance'), ('RESERVED', 'Reserved'), ('OUT_OF_SERVICE', 'Out of Service')], default='AVAILABLE', max_length=20)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'parking_slots',
                'ordering': ['slot_number'],
                'indexes': [models.Index(fields=['status'], name='parking_slo_status_845aae_idx'), models.Index(fields=['slot_number'], name='parking_slo_slot_nu_5a4012_idx')],
            },
        ),
        migrations.CreateModel(
            name='ParkingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('amount_due', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parking_sessions', to='vehicles.vehicle')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parking_sessions', to='parking.parkingslot')),
            ],
            options={
                'db_table': 'parking_sessions',
                'ordering': ['-entry_time'],
                'indexes': [models.Index(fields=['status'], name='parking_ses_status_3fae7b_idx'), models.Index(fields=['vehicle', 'status'], name='parking_ses_vehicle_fa4d90_idx'), models.Index(fields=['entry_time'], name='parking_ses_entry_t_c731d7_idx')],
            },
        ),
    ]
